Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -12,7 +12,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
           java-version: '17'
@@ -20,9 +20,13 @@ jobs:
       - name: Unzip and Build APK
         run: |
           unzip -o Premium3DTimer_Final.zip
-          GRADLE_FILE=$(find . -maxdepth 3 -name "build.gradle" -o -name "build.gradle.kts" | head -n 1)
-          PROJECT_DIR=$(dirname "$GRADLE_FILE")
-          echo "Project directory is: $PROJECT_DIR"
+          SETTINGS_FILE=$(find . -name "settings.gradle" -o -name "settings.gradle.kts" | head -n 1)
+          if [ -z "$SETTINGS_FILE" ]; then
+            echo "settings.gradle not found!"
+            exit 1
+          fi
+          PROJECT_DIR=$(dirname "$SETTINGS_FILE")
+          echo "Found project directory: $PROJECT_DIR"
           cd "$PROJECT_DIR"
           
           if [ ! -f "gradlew" ]; then
